# Generated by Django 5.0.6 on 2024-05-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='image_card',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='image_cover',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='video',
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='image_url',
            field=models.URLField(default='not available'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.CharField(default='not rated', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='stars',
            field=models.TextField(default='unknown'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='length',
            field=models.CharField(max_length=20),
        ),
    ]
