# Generated by Django 5.0.6 on 2024-05-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_movie_python'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='python',
            field=models.ImageField(upload_to='media/movie_images/'),
        ),
    ]
