# Generated by Django 5.0.6 on 2024-05-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_movie_python'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='python',
        ),
        migrations.AddField(
            model_name='movie',
            name='url',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
    ]
