# Generated by Django 5.0.6 on 2024-05-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_movie_python_movie_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='url',
        ),
        migrations.AlterField(
            model_name='movie',
            name='image_url',
            field=models.CharField(max_length=255),
        ),
    ]
