# Generated by Django 5.0.6 on 2024-05-17 20:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_likedmovie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LikedMovie',
            new_name='UserLikedMovie',
        ),
    ]
